using System.IO;
using System.Threading.Tasks;

namespace PoRepoLineTracker.API.Services
{
    /// <summary>
    /// Counts genuine source lines: blank lines and comment-only lines are excluded, and a file
    /// carrying a machine-generated marker (<c>&lt;auto-generated</c>, "do not edit", etc.) in one
    /// of its first few lines is skipped entirely rather than counted.
    ///
    /// <para>
    /// Applied to every tracked extension uniformly — including the "*" fallback, via a comment-
    /// free instance — on purpose. A prior version gave only .cs this treatment and was reverted
    /// because mixing a comment-stripped extension with raw-counted ones in the same total made
    /// line counts incomparable across languages (see LineCounterTests.cs history). Applying the
    /// same rules everywhere keeps every extension on the same footing.
    /// </para>
    ///
    /// <para>
    /// Comment stripping is line-oriented pattern matching, not a real parser, so a string literal
    /// containing "//" or "#" can be misread as a comment. That is an accepted limitation shared by
    /// every non-parser line counter — the goal is a reasonable approximation of authored code, not
    /// a byte-perfect one.
    /// </para>
    /// </summary>
    public sealed class SourceLineCounter : ILineCounter
    {
        public string FileExtension { get; }

        private readonly string? _lineCommentPrefix;
        private readonly (string Start, string End)? _blockComment;

        /// <summary>
        /// How many of a file's leading lines are scanned for a generated-code marker before
        /// giving up and counting normally. Generous enough to survive a license header sitting
        /// above the marker, small enough that scanning it costs nothing measurable.
        /// </summary>
        private const int GeneratedMarkerScanLines = 20;

        private static readonly string[] GeneratedMarkers =
        [
            "<auto-generated",
            "autogenerated file",
            "auto-generated file",
            "automatically generated",
            "code generated by",
            "generated by the",
            "do not edit this file",
            "do not modify this file",
            "do not edit manually",
            "@generated"
        ];

        public SourceLineCounter(string fileExtension, string? lineCommentPrefix = null, (string Start, string End)? blockComment = null)
        {
            FileExtension = fileExtension;
            _lineCommentPrefix = lineCommentPrefix;
            _blockComment = blockComment;
        }

        /// <summary>
        /// One counter per tracked extension, plus the "*" fallback for anything not listed, so
        /// every extension gets the SAME blank/comment-line exclusion and generated-file skip.
        /// This table replaced 17 individual DI registrations that carried the same data.
        /// </summary>
        public static IReadOnlyList<ILineCounter> DefaultSet()
        {
            // Built from CommentSyntax, which is the single table of which language marks comments
            // how — shared with CodeMetricsAnalyzer so the two cannot disagree about where code
            // stops and commentary starts. This list used to be seventeen constructor calls of
            // which twelve were the byte-identical C-style tuple, and two named a syntax the
            // language does not have.
            //
            // The "*" fallback counts blank lines out and nothing else: with no syntax configured
            // it cannot strip comments, which is the correct behaviour for an unknown language.
            var counters = new List<ILineCounter> { new SourceLineCounter("*") };

            foreach (var extension in CommentSyntax.KnownExtensions)
            {
                var syntax = CommentSyntax.For(extension);
                counters.Add(new SourceLineCounter(extension, syntax.LinePrefix, syntax.Block));
            }

            return counters;
        }

        public async Task<int> CountLinesAsync(Stream stream)
        {
            using var reader = new StreamReader(stream);
            var inBlockComment = false;
            var count = 0;
            var markerLinesScanned = 0;

            string? line;
            while ((line = await reader.ReadLineAsync()) != null)
            {
                if (markerLinesScanned < GeneratedMarkerScanLines)
                {
                    markerLinesScanned++;
                    if (ContainsGeneratedMarker(line))
                    {
                        // Machine-generated — not code written for the app. Discard the whole file
                        // rather than whatever was counted so far.
                        return 0;
                    }
                }

                var codeOnly = StripComment(line, ref inBlockComment);
                if (!string.IsNullOrWhiteSpace(codeOnly))
                {
                    count++;
                }
            }

            return count;
        }

        private static bool ContainsGeneratedMarker(string line)
        {
            foreach (var marker in GeneratedMarkers)
            {
                if (line.Contains(marker, System.StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
            return false;
        }

        /// <summary>
        /// Strips block- and line-comment text from a single physical line, tracking whether the
        /// line ends inside an unclosed block comment via <paramref name="inBlockComment"/>.
        /// </summary>
        private string StripComment(string line, ref bool inBlockComment)
        {
            var working = line;

            if (inBlockComment)
            {
                if (_blockComment is not { } activeBlock)
                {
                    // No block-comment syntax configured for this extension — nothing to close.
                    inBlockComment = false;
                    return working;
                }

                var endIdx = working.IndexOf(activeBlock.End, System.StringComparison.Ordinal);
                if (endIdx < 0)
                {
                    // Still inside the comment — the whole line is non-code.
                    return string.Empty;
                }

                working = working[(endIdx + activeBlock.End.Length)..];
                inBlockComment = false;
            }

            if (_blockComment is { } block)
            {
                while (true)
                {
                    var startIdx = working.IndexOf(block.Start, System.StringComparison.Ordinal);
                    if (startIdx < 0) break;

                    var searchFrom = startIdx + block.Start.Length;
                    var endIdx = working.IndexOf(block.End, searchFrom, System.StringComparison.Ordinal);
                    if (endIdx < 0)
                    {
                        working = working[..startIdx];
                        inBlockComment = true;
                        break;
                    }

                    working = string.Concat(working.AsSpan(0, startIdx), working.AsSpan(endIdx + block.End.Length));
                }
            }

            if (_lineCommentPrefix is { } prefix)
            {
                var idx = working.IndexOf(prefix, System.StringComparison.Ordinal);
                if (idx >= 0)
                {
                    working = working[..idx];
                }
            }

            return working;
        }
    }
}
