using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace PoRepoLineTracker.Infrastructure.FileFilters;

public class FileIgnoreFilter : IFileIgnoreFilter
{
    private readonly ILogger<FileIgnoreFilter> _logger;
    private readonly HashSet<string> _packageManagerFiles;
    private readonly HashSet<string> _buildOutputExtensions;
    private readonly HashSet<string> _autoGeneratedExtensions;
    private readonly HashSet<string> _autoGeneratedFilePatterns;
    private readonly string _migrationFolderPattern;
    private readonly HashSet<string> _thirdPartyJsExtensions;
    private readonly HashSet<string> _thirdPartyJsPatterns;
    private readonly HashSet<string> _ideConfigExtensions;
    private readonly HashSet<string> _ideConfigFiles;
    private readonly HashSet<string> _webAssetExtensions;
    private readonly HashSet<string> _testDataExtensions;
    private readonly HashSet<string> _directoryPatternsToIgnore;

    public FileIgnoreFilter(ILogger<FileIgnoreFilter> logger)
    {
        _logger = logger;

        // Category 1: Package Manager Files
        _packageManagerFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "packages.config", "package-lock.json", "yarn.lock", "paket.lock", "paket.dependencies"
        };

        // Category 2: Build Output & Compiled Files
        _buildOutputExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            ".dll", ".exe", ".pdb", ".obj", ".cache", ".lib", ".exp", ".ilk", ".idb", ".nupkg"
        };

        // Category 3: Auto-Generated Code Files
        _autoGeneratedExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            ".designer.cs", ".g.cs", ".g.i.cs", ".designer.vb", ".g.vb"
        };

        _autoGeneratedFilePatterns = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "reference.cs", "temporarygeneratedfile", "assemblyinfo"
        };

        // Category 4: Database Migration Files (in Migrations/ folder)
        _migrationFolderPattern = "migrations/";

        // Category 5: Third-Party JavaScript Libraries
        _thirdPartyJsExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            ".min.js", ".min.css"
        };

        _thirdPartyJsPatterns = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "jquery", "bootstrap"
        };

        // Category 6: IDE and Tool Configuration
        _ideConfigExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            ".user", ".suo", ".vspscc", ".vssscc"
        };

        _ideConfigFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "launchsettings.json"
        };

        // Category 8: Web Assets from Package Managers
        _webAssetExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            ".woff", ".woff2", ".ttf", ".eot", ".otf"
        };

        // Category 10: Test Data and Mock Files
        _testDataExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            ".resx", ".settings", ".resources"
        };

        // Directory patterns to ignore
        _directoryPatternsToIgnore = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            // Category 2: Build Output directories
            "bin/", "obj/", "debug/", "release/",
            // Category 5: Third-party JS directories
            "node_modules/", "bower_components/", "jspm_packages/", "typings/",
            // Category 6: IDE directories
            ".vs/", ".vscode/", ".idea/",
            // Category 8: Web asset directories
            "wwwroot/lib/",
            // Always ignore .git
            ".git/",
            // Category 1: Package directories
            "packages/"
        };
    }

    public bool ShouldIgnoreFile(string fileName, string filePath)
    {
        var fileNameLower = fileName.ToLowerInvariant();
        var fileExtension = Path.GetExtension(fileNameLower);

        // Category 1: Check package manager files by exact name
        if (_packageManagerFiles.Contains(fileNameLower))
        {
            _logger.LogDebug("Ignoring package manager file: {FileName}", fileName);
            return true;
        }

        // Category 2: Check build output extensions
        if (_buildOutputExtensions.Any(ext => fileNameLower.EndsWith(ext)))
        {
            _logger.LogDebug("Ignoring build output file: {FileName}", fileName);
            return true;
        }

        // Category 3: Check auto-generated file extensions
        if (_autoGeneratedExtensions.Any(ext => fileNameLower.EndsWith(ext)))
        {
            _logger.LogDebug("Ignoring auto-generated file: {FileName}", fileName);
            return true;
        }

        // Category 3: Check auto-generated file patterns
        if (_autoGeneratedFilePatterns.Any(pattern => fileNameLower.Contains(pattern)))
        {
            _logger.LogDebug("Ignoring auto-generated file: {FileName}", fileName);
            return true;
        }

        // Category 4: Check database migration files
        if (filePath.ToLowerInvariant().Contains(_migrationFolderPattern))
        {
            _logger.LogDebug("Ignoring migration file: {FileName}", fileName);
            return true;
        }

        // Category 5: Check third-party JS extensions
        if (_thirdPartyJsExtensions.Any(ext => fileNameLower.EndsWith(ext)))
        {
            _logger.LogDebug("Ignoring third-party JS file: {FileName}", fileName);
            return true;
        }

        // Category 5: Check third-party JS patterns
        if (_thirdPartyJsPatterns.Any(pattern => fileNameLower.Contains(pattern)))
        {
            _logger.LogDebug("Ignoring third-party JS library file: {FileName}", fileName);
            return true;
        }

        // Category 6: Check IDE config extensions
        if (_ideConfigExtensions.Any(ext => fileNameLower.EndsWith(ext)))
        {
            _logger.LogDebug("Ignoring IDE config file: {FileName}", fileName);
            return true;
        }

        // Category 6: Check IDE config files by name
        if (_ideConfigFiles.Contains(fileNameLower))
        {
            _logger.LogDebug("Ignoring IDE config file: {FileName}", fileName);
            return true;
        }

        // Category 8: Check web asset extensions
        if (_webAssetExtensions.Any(ext => fileNameLower.EndsWith(ext)))
        {
            _logger.LogDebug("Ignoring web asset file: {FileName}", fileName);
            return true;
        }

        // Category 10: Check test data extensions
        if (_testDataExtensions.Any(ext => fileNameLower.EndsWith(ext)))
        {
            _logger.LogDebug("Ignoring test data file: {FileName}", fileName);
            return true;
        }

        return false;
    }

    public bool ShouldIgnoreDirectory(string directoryPath)
    {
        var normalizedPath = directoryPath.Replace("\\", "/").ToLowerInvariant() + "/";

        bool shouldIgnore = _directoryPatternsToIgnore.Any(pattern =>
            normalizedPath.EndsWith(pattern) ||
            normalizedPath.Contains("/" + pattern) ||
            normalizedPath.StartsWith(pattern));

        if (shouldIgnore)
        {
            _logger.LogDebug("Ignoring directory: {DirectoryName} (matches ignore pattern)", directoryPath);
        }

        return shouldIgnore;
    }
}
