using System.Text;
using FluentAssertions;

namespace PoRepoLineTracker.Unit;

// SourceLineCounter replaces the old DefaultLineCounter/CSharpLineCounter split. A prior version
// gave only .cs comment/blank-line exclusion and was reverted because mixing a comment-stripped
// extension with raw-counted ones made totals incomparable across languages. SourceLineCounter is
// registered once per extension (including "*" with no comment syntax as the fallback), so the
// same rules apply everywhere — these tests exercise it through each syntax it is configured with.
public class SourceLineCounterTests
{
    // "*" has no configured comment syntax: blanks are still excluded, and a literal "//" is
    // just content, not a comment.
    [Theory]
    [InlineData("", 0)]
    [InlineData("line 1\n\n   \nline 3\n", 2)]
    [InlineData("// looks like a comment but isn't here\n", 1)]
    public async Task CountLinesAsync_NoCommentSyntax_CountsNonBlankLinesVerbatim(string content, int expected)
    {
        var sut = new SourceLineCounter("*");
        var result = await sut.CountLinesAsync(Stream(content));
        result.Should().Be(expected);
    }

    [Fact]
    public async Task CountLinesAsync_CStyle_ExcludesLineCommentOnlyLines()
    {
        var sut = new SourceLineCounter(".cs", "//", ("/*", "*/"));
        var result = await sut.CountLinesAsync(Stream("using System;\n// a comment\nvar x = 1;\n"));
        result.Should().Be(2);
    }

    [Fact]
    public async Task CountLinesAsync_CStyle_KeepsCodeBeforeTrailingLineComment()
    {
        var sut = new SourceLineCounter(".cs", "//", ("/*", "*/"));
        var result = await sut.CountLinesAsync(Stream("var x = 1; // trailing comment\n"));
        result.Should().Be(1);
    }

    [Fact]
    public async Task CountLinesAsync_CStyle_ExcludesMultiLineBlockComment()
    {
        var sut = new SourceLineCounter(".cs", "//", ("/*", "*/"));
        var content = "var before = 1;\n/* start of\n a block\n comment */\nvar after = 2;\n";
        var result = await sut.CountLinesAsync(Stream(content));
        result.Should().Be(2);
    }

    [Fact]
    public async Task CountLinesAsync_CStyle_CountsLineWithCodeAfterBlockCommentCloses()
    {
        var sut = new SourceLineCounter(".cs", "//", ("/*", "*/"));
        var content = "/* comment\n spanning */ var x = 1;\n";
        var result = await sut.CountLinesAsync(Stream(content));
        result.Should().Be(1);
    }

    // The other configured syntaxes: hash-style (Python) and markup-style (HTML), which has no
    // line-comment token at all.
    [Fact]
    public async Task CountLinesAsync_HashAndMarkupSyntaxes_ExcludeTheirComments()
    {
        var python = new SourceLineCounter(".py", "#");
        (await python.CountLinesAsync(Stream("import os\n# a comment\nx = 1\n"))).Should().Be(2);

        var html = new SourceLineCounter(".html", null, ("<!--", "-->"));
        (await html.CountLinesAsync(Stream("<div>content</div>\n<!-- a comment -->\n"))).Should().Be(1);
    }

    [Theory]
    [InlineData("<auto-generated>\nusing System;\nclass Foo {}\n")]
    [InlineData("// This code was generated by a tool.\n// Do not edit this file directly.\nusing System;\n")]
    public async Task CountLinesAsync_GeneratedFileMarker_ReturnsZero(string content)
    {
        var sut = new SourceLineCounter(".cs", "//", ("/*", "*/"));
        var result = await sut.CountLinesAsync(Stream(content));
        result.Should().Be(0);
    }

    [Fact]
    public async Task CountLinesAsync_GeneratedMarkerFarBelowScanWindow_IsNotDetected()
    {
        // The marker scan only looks at the leading handful of lines — a marker buried deep in an
        // otherwise-normal file (unlikely in practice) does not zero out the real content above
        // it. The marker line itself is still a "//" comment, so it does not add to the count
        // either — only the 25 padding lines do.
        var sut = new SourceLineCounter(".cs", "//", ("/*", "*/"));
        var padding = string.Concat(Enumerable.Repeat("var x = 1;\n", 25));
        var content = padding + "// <auto-generated>\n";
        var result = await sut.CountLinesAsync(Stream(content));
        result.Should().Be(25);
    }

    // ─── DefaultSet wiring ───────────────────────────────────────────────────
    //
    // The registrations themselves are worth asserting, not just the stripping logic: the set was
    // seventeen near-identical constructor calls, and two of them named a comment syntax the
    // language does not have.

    private static ILineCounter CounterFor(string extension) =>
        SourceLineCounter.DefaultSet().Single(c => c.FileExtension == extension);

    /// <summary>
    /// CSS has no line-comment syntax — only <c>/* */</c>. It was registered with "//", which
    /// truncated every line from the first "//" onwards, so a URL was cut at its scheme and a line
    /// holding nothing but one counted as blank.
    /// </summary>
    [Fact]
    public async Task DefaultSet_Css_DoesNotTreatDoubleSlashAsAComment()
    {
        var result = await CounterFor(".css").CountLinesAsync(
            Stream("@import url(https://fonts.example.com/x.css);\nbody { color: red; }\n"));

        result.Should().Be(2, "the @import line is code, not a comment");
    }

    [Fact]
    public async Task DefaultSet_Css_StillStripsBlockComments()
    {
        var result = await CounterFor(".css").CountLinesAsync(
            Stream("/* a note */\nbody { color: red; }\n"));

        result.Should().Be(1);
    }

    /// <summary>
    /// Sass and Less DO have "//", unlike plain CSS — which is exactly why they cannot share a
    /// registration with it.
    /// </summary>
    [Fact]
    public async Task DefaultSet_Scss_DoesTreatDoubleSlashAsAComment()
    {
        var result = await CounterFor(".scss").CountLinesAsync(
            Stream("// a note\n$brand: red;\n"));

        result.Should().Be(1);
    }

    /// <summary>
    /// Razor comments are <c>@* *@</c>; "//" is not one. Registered with "//", any markup line
    /// containing a URL or an xmlns was cut short.
    /// </summary>
    [Fact]
    public async Task DefaultSet_Razor_DoesNotTreatDoubleSlashAsAComment()
    {
        var result = await CounterFor(".razor").CountLinesAsync(
            Stream("<a href=\"https://example.com\">x</a>\n<p>hello</p>\n"));

        result.Should().Be(2);
    }

    [Fact]
    public void DefaultSet_RegistersEveryDefaultExtension_PlusTheFallback()
    {
        var registered = SourceLineCounter.DefaultSet().Select(c => c.FileExtension).ToList();

        registered.Should().Contain("*", "an unknown extension still needs blank-line exclusion");
        registered.Should().OnlyHaveUniqueItems("a duplicate registration would make the counter map ambiguous");
        registered.Should().Contain(UserPreferences.DefaultFileExtensions,
            "every extension counted by default must have a counter, or it silently falls back to '*'");
    }

    private static MemoryStream Stream(string content) => new(Encoding.UTF8.GetBytes(content));
}
