using System.Text;
using FluentAssertions;

namespace PoRepoLineTracker.Unit;

// SourceLineCounter replaces the old DefaultLineCounter/CSharpLineCounter split. A prior version
// gave only .cs comment/blank-line exclusion and was reverted because mixing a comment-stripped
// extension with raw-counted ones made totals incomparable across languages. SourceLineCounter is
// registered once per extension (including "*" with no comment syntax as the fallback), so the
// same rules apply everywhere — these tests exercise it through each syntax it is configured with.
public class SourceLineCounterTests
{
    [Fact]
    public async Task CountLinesAsync_NoCommentSyntax_CountsNonBlankLinesVerbatim()
    {
        var sut = new SourceLineCounter("*");
        (await sut.CountLinesAsync(Stream(""))).Should().Be(0);
        (await sut.CountLinesAsync(Stream("line 1\n\n   \nline 3\n"))).Should().Be(2);
        (await sut.CountLinesAsync(Stream("// looks like a comment but isn't here\n"))).Should().Be(1);
    }

    [Fact]
    public async Task CountLinesAsync_CStyleAndOtherSyntaxes_CorrectlyFiltersComments()
    {
        var cstyle = new SourceLineCounter(".cs", "//", ("/*", "*/"));
        (await cstyle.CountLinesAsync(Stream("using System;\n// a comment\nvar x = 1;\n"))).Should().Be(2);
        (await cstyle.CountLinesAsync(Stream("var x = 1; // trailing comment\n"))).Should().Be(1);
        (await cstyle.CountLinesAsync(Stream("var before = 1;\n/* start of\n a block\n comment */\nvar after = 2;\n"))).Should().Be(2);
        (await cstyle.CountLinesAsync(Stream("/* comment\n spanning */ var x = 1;\n"))).Should().Be(1);

        var python = new SourceLineCounter(".py", "#");
        (await python.CountLinesAsync(Stream("import os\n# a comment\nx = 1\n"))).Should().Be(2);

        var html = new SourceLineCounter(".html", null, ("<!--", "-->"));
        (await html.CountLinesAsync(Stream("<div>content</div>\n<!-- a comment -->\n"))).Should().Be(1);
    }

    [Fact]
    public async Task CountLinesAsync_GeneratedFileMarkers_HandledCorrectly()
    {
        var sut = new SourceLineCounter(".cs", "//", ("/*", "*/"));
        (await sut.CountLinesAsync(Stream("<auto-generated>\nusing System;\nclass Foo {}\n"))).Should().Be(0);
        (await sut.CountLinesAsync(Stream("// This code was generated by a tool.\n// Do not edit this file directly.\nusing System;\n"))).Should().Be(0);

        var padding = string.Concat(Enumerable.Repeat("var x = 1;\n", 25));
        var content = padding + "// <auto-generated>\n";
        (await sut.CountLinesAsync(Stream(content))).Should().Be(25);
    }

    // ─── DefaultSet wiring ───────────────────────────────────────────────────

    private static ILineCounter CounterFor(string extension) =>
        SourceLineCounter.DefaultSet().Single(c => c.FileExtension == extension);

    [Fact]
    public async Task DefaultSet_SpecificLanguageSyntaxes_HandledAccurately()
    {
        (await CounterFor(".css").CountLinesAsync(
            Stream("@import url(https://fonts.example.com/x.css);\nbody { color: red; }\n"))).Should().Be(2);
        (await CounterFor(".css").CountLinesAsync(
            Stream("/* a note */\nbody { color: red; }\n"))).Should().Be(1);
        (await CounterFor(".scss").CountLinesAsync(
            Stream("// a note\n$brand: red;\n"))).Should().Be(1);
        (await CounterFor(".razor").CountLinesAsync(
            Stream("<a href=\"https://example.com\">x</a>\n<p>hello</p>\n"))).Should().Be(2);
    }

    [Fact]
    public void DefaultSet_RegistersEveryDefaultExtension_PlusTheFallback()
    {
        var registered = SourceLineCounter.DefaultSet().Select(c => c.FileExtension).ToList();

        registered.Should().Contain("*", "an unknown extension still needs blank-line exclusion");
        registered.Should().OnlyHaveUniqueItems("a duplicate registration would make the counter map ambiguous");
        registered.Should().Contain(UserPreferences.DefaultFileExtensions,
            "every extension counted by default must have a counter, or it silently falls back to '*'");
    }

    private static MemoryStream Stream(string content) => new(Encoding.UTF8.GetBytes(content));
}
